[access_point]
ap ansible_host=192.168.1.1

[access_point:vars]
ansible_user=webui
ansible_password=cisco
ansible_network_os=ios
#the operating system of the network device
#ansible needs to know which module collection touse for routers and switch
ansible_connection=network_cli
 #a protocol used to connect to a devices
#network devices via network_cli.

